# Generated by Django 5.1.6 on 2025-06-08 15:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('model_wrf_stilt', '0001_initial'), ('model_wrf_stilt', '0002_remove_modelwrfstilt_receptor_modelwrfstilt_dx_and_more'), ('model_wrf_stilt', '0003_modelwrfstilt_interval_seconds'), ('model_wrf_stilt', '0004_modelwrfstilt_obsdata_url_config_and_more'), ('model_wrf_stilt', '0005_alter_modelwrfstilt_obsdata_url_config'), ('model_wrf_stilt', '0006_remove_pollutantsource_description_and_more'), ('model_wrf_stilt', '0007_modelwrfstilt_data_source_modelwrfstilt_fnl_url_and_more'), ('model_wrf_stilt', '0008_modelwrfstilt_stilt_wrf_dom'), ('model_wrf_stilt', '0009_modelwrfstilt_data_delay_hours'), ('model_wrf_stilt', '0010_pollutantsource_created_at_and_more'), ('model_wrf_stilt', '0011_remove_pollutantsource_created_at_and_more'), ('model_wrf_stilt', '0012_alter_receptor_region'), ('model_wrf_stilt', '0013_alter_modelwrfstilt_obsgrid_enabled')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='选中表示删除', verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='区域名称')),
                ('xmn', models.FloatField(verbose_name='最小经度')),
                ('xmx', models.FloatField(verbose_name='最大经度')),
                ('ymn', models.FloatField(verbose_name='最小纬度')),
                ('ymx', models.FloatField(verbose_name='最大纬度')),
                ('geojson', models.TextField(blank=True, null=True, verbose_name='区域边界 GeoJSON')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域管理',
                'db_table': 'w_region',
            },
        ),
        migrations.CreateModel(
            name='PollutantSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='选中表示删除', verbose_name='是否删除')),
                ('name', models.CharField(help_text='污染源名称', max_length=100, verbose_name='污染源名称')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('categoty', models.CharField(blank=True, help_text='污染源类别', max_length=50, null=True, verbose_name='污染源类别')),
                ('diameter', models.FloatField(blank=True, help_text='直径', null=True, verbose_name='直径')),
                ('emission_type', models.CharField(blank=True, help_text='排放类型', max_length=50, null=True, verbose_name='排放类型')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='高度（米）')),
                ('pm10', models.FloatField(blank=True, null=True, verbose_name='PM10')),
                ('pm25', models.FloatField(blank=True, null=True, verbose_name='PM2.5')),
                ('utm_zoom50_x', models.FloatField(blank=True, help_text='UTM_X', null=True, verbose_name='UTM_X')),
                ('utm_zoom50_y', models.FloatField(blank=True, help_text='UTM_Y', null=True, verbose_name='UTM_Y')),
            ],
            options={
                'verbose_name': '污染源',
                'verbose_name_plural': '污染源管理',
                'db_table': 'w_pollutant_source',
            },
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='选中表示删除', verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, verbose_name='受体名称')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('height', models.FloatField(verbose_name='高度（米）')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptors', to='model_wrf_stilt.region', verbose_name='所属区域')),
            ],
            options={
                'verbose_name': '受体',
                'verbose_name_plural': '受体管理',
                'db_table': 'w_receptor',
            },
        ),
        migrations.CreateModel(
            name='ModelWrfStilt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='选中表示删除', verbose_name='是否删除')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='letters_only', message='只允许使用大小写英文字母', regex='^[a-zA-Z]+$')], verbose_name='模型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述信息')),
                ('xres', models.FloatField(default=0.001, verbose_name='X方向分辨率')),
                ('yres', models.FloatField(default=0.001, verbose_name='Y方向分辨率')),
                ('n_cores', models.IntegerField(default=8, verbose_name='计算核心数')),
                ('wrf_file_retention_days', models.IntegerField(default=365, verbose_name='WRF文件保留天数')),
                ('i_parent_start', models.CharField(max_length=100, verbose_name='i_parent_start')),
                ('j_parent_start', models.CharField(max_length=100, verbose_name='j_parent_start')),
                ('e_we', models.CharField(max_length=100, verbose_name='e_we')),
                ('e_sn', models.CharField(max_length=100, verbose_name='e_sn')),
                ('dx', models.IntegerField(default=27000, verbose_name='dx(m)')),
                ('dy', models.IntegerField(default=27000, verbose_name='dy(m)')),
                ('max_dom', models.IntegerField(default=4, verbose_name='嵌套域数')),
                ('obsgrid_enabled', models.BooleanField(default=False, verbose_name='是否启用obsgrid')),
                ('interval_seconds', models.IntegerField(default=21600, verbose_name='时间间隔(秒)')),
                ('obsdata_url_config', models.JSONField(blank=True, null=True, verbose_name='地面站请求URL配置')),
                ('data_source', models.CharField(choices=[('fnl', 'fnl'), ('gfs', 'gfs')], default='gfs', max_length=100, verbose_name='数据源')),
                ('fnl_url', models.URLField(default='https://data.rda.ucar.edu/d083002/grib2/', verbose_name='fnl数据源URL')),
                ('gfs_url', models.URLField(default='https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/', verbose_name='gfs数据源URL')),
                ('stilt_wrf_dom', models.IntegerField(default=3, verbose_name='计算STILT的WRF域数')),
                ('data_delay_hours', models.IntegerField(default=0, verbose_name='延迟小时数')),
            ],
            options={
                'verbose_name': 'WRF-STILT模型',
                'verbose_name_plural': 'WRF-STILT模型管理',
                'db_table': 'w_model_config',
            },
        ),
    ]
