# Generated by Django 5.1.6 on 2025-07-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0001_squashed_0013_alter_modelwrfstilt_obsgrid_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwrfstilt',
            name='obsgrid_upper_air_url',
            field=models.URLField(default='https://daejeon-kreonet-net.nationalresearchplatform.org:8443/ncar/rda/d351000/little_r/', verbose_name='obsgrid高空大气数据源URL'),
        ),
        migrations.AlterField(
            model_name='modelwrfstilt',
            name='data_source',
            field=models.CharField(blank=True, choices=[('fnl', 'fnl'), ('gfs', 'gfs')], max_length=100, null=True, verbose_name='数据源'),
        ),
        migrations.AlterField(
            model_name='modelwrfstilt',
            name='obsdata_url_config',
            field=models.JSONField(blank=True, null=True, verbose_name='obsgrid地面站请求URL配置'),
        ),
    ]
