# Generated by Django 5.1.6 on 2025-07-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0014_modelwrfstilt_obsgrid_upper_air_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwrfstilt',
            name='data_source',
            field=models.CharField(choices=[('fnl', 'fnl'), ('gfs', 'gfs')], default='gfs', max_length=100, verbose_name='数据源'),
        ),
    ]
