# Generated by Django 5.1.6 on 2025-07-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0015_alter_modelwrfstilt_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwrfstilt',
            name='aermod_anchorxy',
            field=models.CharField(blank=True, help_text='example: 509006 4068596 509006 4068596 50 4', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='modelwrfstilt',
            name='aermod_domainxy',
            field=models.CharField(blank=True, help_text='example: 430399 3983176 50 587613 4154016 50', max_length=200, null=True),
        ),
    ]
