# Generated by Django 5.1.6 on 2025-07-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0016_modelwrfstilt_aermod_anchorxy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutantsource',
            name='categoty',
        ),
        migrations.RemoveField(
            model_name='pollutantsource',
            name='pm10',
        ),
        migrations.RemoveField(
            model_name='pollutantsource',
            name='pm25',
        ),
        migrations.RemoveField(
            model_name='pollutantsource',
            name='utm_zoom50_x',
        ),
        migrations.RemoveField(
            model_name='pollutantsource',
            name='utm_zoom50_y',
        ),
        migrations.AddField(
            model_name='pollutantsource',
            name='exit_velocity',
            field=models.FloatField(blank=True, default=10.0, help_text='烟囱出口速度（m/s）', null=True, verbose_name='烟囱出口速度'),
        ),
        migrations.AddField(
            model_name='pollutantsource',
            name='pm10_emis',
            field=models.FloatField(blank=True, null=True, verbose_name='PM10排放'),
        ),
        migrations.AddField(
            model_name='pollutantsource',
            name='stack_temp',
            field=models.FloatField(blank=True, default=400.0, help_text='烟囱气体温度（K）', null=True, verbose_name='烟囱气体温度'),
        ),
        migrations.AddField(
            model_name='pollutantsource',
            name='time_type',
            field=models.CharField(choices=[('hourly', '小时'), ('yearly', '年')], default='yearly', help_text='时间类型', max_length=50, verbose_name='时间类型'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='diameter',
            field=models.FloatField(blank=True, default=1.0, help_text='烟囱直径', null=True, verbose_name='烟囱直径'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='emission_type',
            field=models.CharField(choices=[('电力生产', '电力生产'), ('电力热力源其他', '电力热力源其他'), ('工业源', '工业源'), ('移动源', '移动源'), ('油品储运销', '油品储运销'), ('生活源', '生活源'), ('农业源', '农业源'), ('扬尘源', '扬尘源'), ('废弃物处理源', '废弃物处理源'), ('生物质开放燃烧源', '生物质开放燃烧源'), ('其他', '其他')], default='其他', help_text='污染源类别', max_length=50, verbose_name='污染源类别'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='height',
            field=models.FloatField(blank=True, default=45.0, null=True, verbose_name='烟囱高度（米）'),
        ),
    ]
