# Generated by Django 5.1.6 on 2025-07-10 03:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0017_remove_pollutantsource_categoty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionContributionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='选中表示删除', verbose_name='是否删除')),
                ('pid', models.IntegerField(verbose_name='污染源ID')),
                ('sid', models.IntegerField(verbose_name='受体点ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('pm10', models.FloatField(default=0.0, verbose_name='PM10浓度')),
                ('dist', models.FloatField(blank=True, null=True, verbose_name='距离')),
            ],
            options={
                'verbose_name': '污染源贡献数据',
                'verbose_name_plural': '污染源贡献数据管理',
                'db_table': 'w_emission_contribution_data',
            },
        ),
    ]
