# Generated by Django 5.1.6 on 2025-07-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0018_emissioncontributiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwrfstilt',
            name='obsgrid_upper_air_url',
            field=models.URLField(blank=True, default='https://daejeon-kreonet-net.nationalresearchplatform.org:8443/ncar/rda/d351000/little_r/', null=True, verbose_name='obsgrid高空大气数据源URL'),
        ),
    ]
