# Generated by Django 5.1.6 on 2025-07-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0019_alter_modelwrfstilt_obsgrid_upper_air_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissioncontributiondata',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_data', to='model_wrf_stilt.pollutantsource', verbose_name='污染源ID'),
        ),
        migrations.AlterField(
            model_name='emissioncontributiondata',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_data', to='model_wrf_stilt.receptor', verbose_name='受体点ID'),
        ),
    ]
