# Generated by Django 5.1.6 on 2025-07-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0020_alter_emissioncontributiondata_pid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissioncontributiondata',
            old_name='pid',
            new_name='pollutant_source',
        ),
        migrations.RenameField(
            model_name='emissioncontributiondata',
            old_name='sid',
            new_name='receptor',
        ),
    ]
