# Generated by Django 5.1.6 on 2025-07-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0021_rename_pid_emissioncontributiondata_pollutant_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissioncontributiondata',
            name='pm10',
        ),
        migrations.AddField(
            model_name='emissioncontributiondata',
            name='emis_rate',
            field=models.FloatField(default=0.0, verbose_name='贡献占比%'),
        ),
        migrations.AddField(
            model_name='emissioncontributiondata',
            name='emis_value',
            field=models.FloatField(default=0.0, verbose_name='贡献值'),
        ),
    ]
