# Generated by Django 5.1.6 on 2025-07-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0022_remove_emissioncontributiondata_pm10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissioncontributiondata',
            name='emis_rate_s',
            field=models.FloatField(default=0.0, verbose_name='敏感性贡献占比%'),
        ),
        migrations.AddField(
            model_name='emissioncontributiondata',
            name='emis_value_s',
            field=models.FloatField(default=0.0, verbose_name='敏感性贡献值'),
        ),
    ]
