# Generated by Django 5.1.6 on 2025-07-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0023_emissioncontributiondata_emis_rate_s_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelwrfstilt',
            name='aermap_datafile',
            field=models.FileField(blank=True, help_text='上传AERMAP数据文件tif', null=True, upload_to='aermap_data.tif', verbose_name='AERMAP数据文件tif'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='diameter',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='烟囱直径'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='emission_type',
            field=models.CharField(choices=[('电力生产', '电力生产'), ('电力热力源其他', '电力热力源其他'), ('工业源', '工业源'), ('移动源', '移动源'), ('油品储运销', '油品储运销'), ('生活源', '生活源'), ('农业源', '农业源'), ('扬尘源', '扬尘源'), ('废弃物处理源', '废弃物处理源'), ('生物质开放燃烧源', '生物质开放燃烧源'), ('其他', '其他')], default='其他', max_length=50, verbose_name='污染源类别'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='exit_velocity',
            field=models.FloatField(blank=True, default=10.0, null=True, verbose_name='烟囱出口速度（m/s）'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='污染源名称'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='stack_temp',
            field=models.FloatField(blank=True, default=400.0, null=True, verbose_name='烟囱气体温度（K）'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='time_type',
            field=models.CharField(choices=[('hourly', '小时'), ('yearly', '年')], default='yearly', max_length=50, verbose_name='时间类型'),
        ),
    ]
