# Generated by Django 5.1.6 on 2025-07-20 14:51

import apps.model_wrf_stilt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0024_modelwrfstilt_aermap_datafile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelwrfstilt',
            name='aermap_datafile',
            field=models.FileField(blank=True, help_text='上传AERMAP数据文件tif', null=True, upload_to=apps.model_wrf_stilt.models.fixed_aermap_path, verbose_name='AERMAP数据文件tif'),
        ),
    ]
