# Generated by Django 5.1.6 on 2025-08-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0025_alter_modelwrfstilt_aermap_datafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutantsource',
            name='pm10_emis',
        ),
        migrations.AddField(
            model_name='pollutantsource',
            name='emis_value',
            field=models.FloatField(blank=True, null=True, verbose_name='污染源排放量(t)'),
        ),
        migrations.AlterField(
            model_name='modelwrfstilt',
            name='obsgrid_upper_air_url',
            field=models.URLField(blank=True, default='https://daejeon-kreonet-net.nationalresearchplatform.org:8443/ncar/rda/d351000/little_r/', help_text='设置为空则不启用obsgrid高空大气数据', null=True, verbose_name='obsgrid高空大气数据源URL'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='diameter',
            field=models.FloatField(blank=True, default=1.0, null=True, verbose_name='烟囱内径(m)'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='exit_velocity',
            field=models.FloatField(blank=True, default=10.0, null=True, verbose_name='排气速度(m/s)'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='height',
            field=models.FloatField(blank=True, default=45.0, null=True, verbose_name='烟囱高度(m)'),
        ),
        migrations.AlterField(
            model_name='pollutantsource',
            name='stack_temp',
            field=models.FloatField(blank=True, default=400.0, null=True, verbose_name='排气温度(K)'),
        ),
    ]
