# Generated by Django 5.1.6 on 2025-08-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_wrf_stilt', '0026_remove_pollutantsource_pm10_emis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emissioncontributiondata',
            name='pollutant_source',
        ),
        migrations.RemoveField(
            model_name='emissioncontributiondata',
            name='receptor',
        ),
        migrations.RemoveField(
            model_name='modelwrfstilt',
            name='aermap_datafile',
        ),
        migrations.RemoveField(
            model_name='modelwrfstilt',
            name='aermod_anchorxy',
        ),
        migrations.RemoveField(
            model_name='modelwrfstilt',
            name='aermod_domainxy',
        ),
        migrations.DeleteModel(
            name='PollutantSource',
        ),
        migrations.DeleteModel(
            name='EmissionContributionData',
        ),
    ]
